### ISSUE TITLE
Update Readme.md with instructions on setting up app

### ISSUE THREAD

**Issue by medic-code** [alexandria-reader/frontend#287]
**Is your feature request related to a problem? Please describe.**
Currently the project has no section on the readme for local setting up the project for others to contribute.

**Describe the solution you'd like**
An update to the readme for clear instructions on how to set up the project locally.

**Comment by eamon0989** [comment]
Hey Aaron, thanks for creating this issue! I added some basic instructions to the README in my latest PR, but due to the lack of tests in the frontend I haven't had time to make sure everything is working correctly, so it hasn't been merged yet. Here's the link to the updated [README](https://github.com/alexandria-reader/frontend/blob/868ea272ae80ec9c83d22f6f3aed2bcd7ae1b6a9/README.md) from the currently open PR.

**Comment by medic-code** [comment]
Thanks Eamon, no worries at all. I couldn't find the .env sample in the repo but appreciate that its an open PR. I've installed the dependencies and can get it running locally but need the .env. sample in order to sign up locally (Having done a quick look through the sign up code).
